### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Akifumi-Tsukada** [Akifumi-Tsukada/protospace-34710#1]
# URL
https://protospace-34710.herokuapp.com/

**Comment by takumi0530** [comment]
@Akifumi-Tsukada さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [ ] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
自身が投稿したプロトタイプでのみエラー画面に遷移してしまいます。
<img width="646" alt="スクリーンショット 2021-04-29 14 13 02" src="https://user-images.githubusercontent.com/76197191/116505167-2d931580-a8f5-11eb-8e5b-f5f0d3a4a415.png">

### **[ご確認をお願い致します]**

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
「test2」というユーザーのみ、ユーザー詳細ページに遷移しようとするとエラー画面が出てしまいます。すでにユーザー情報を削除しているかをこちらで判断できなかったため、併せてご確認をお願い致します。
**※こちら意図していない動作である場合は修正をお願い致します。**

<img width="445" alt="スクリーンショット 2021-04-29 14 17 14" src="https://user-images.githubusercontent.com/76197191/116505355-a1352280-a8f5-11eb-89cc-9bc8eca644bf.png">
<img width="630" alt="スクリーンショット 2021-04-29 14 17 19" src="https://user-images.githubusercontent.com/76197191/116505356-a2664f80-a8f5-11eb-9190-2d54b1178450.png">


修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Akifumi-Tsukada** [comment]
レビューありがとうございます。
コメントフォームの挙動は修正が完了しました。

また「test2」のユーザーの詳細ページが開けない原因がわからないです。新たに「test3」を作ってみましたが、こちらは詳細ページが開けます。ローカル環境では既存のユーザーも新らたに登録したユーザーでもエラーにならなかったので、これだけがわからないです。

ご確認お願いします。

**Comment by takumi0530** [comment]
@Akifumi-Tsukada さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できましたのでLGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀


### **[補足]**

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
新しく「test」「テスト」「aaa」というユーザー名でアカウントを作成いたしました。その中でも「test」のユーザーのみ「test2」と同じ挙動をしました。（別スタッフが作成した「test」というユーザー名のアカウントですと、問題なくユーザー詳細ページに遷移できました。）
**※こちらですが、原因不明のため要件達成とみなしております。**


https://user-images.githubusercontent.com/76197191/116639814-56beaf00-a9a4-11eb-8ffd-f8c2ceda911c.mov

**Comment by Akifumi-Tsukada** [comment]
ありがとうございました。原因の方もこちらで今までの作業やソースコードを見直しておきます。
最終課題では不具合が起きないように注意して進めます。
